const phrases =
[
    "aaach"
    ,"ace"
    ,"ahhhhhh"
    ,"ah-rooooo"
    ,"airmail"
    ,"aiya"
    ,"alrighty"
    ,"alpha"
    ,"amigo"
    ,"arfer"
    ,"ayup yup"
    ,"ayyeeee"
    ,"ah-Choo"
    ,"aye aye"
    ,"as if"
    ,"baboom"
    ,"baaaby"
    ,"baaaffo"
    ,"baaa man"
    ,"baa-dabing"
    ,"bawwww"
    ,"b-b-buddy"
    ,"beach bum"
    ,"beaker"
    ,"bigfoot"
    ,"bingo"
    ,"bitty"
    ,"bleeeeeck"
    ,"bleh eh eh"
    ,"blih"
    ,"bloop"
    ,"blurp"
    ,"boing"
    ,"bonbon"
    ,"boosh"
    ,"bo peep"
    ,"bowes"
    ,"brah"
    ,"brrmph"
    ,"brrrrrrrrr"
    ,"buckaroo"
    ,"bucko"
    ,"bud"
    ,"bunyip"
    ,"burrrn"
    ,"burrup"
    ,"buh-kay"
    ,"bun bun"
    ,"bow-WOW"
    ,"bzzert"
    ,"b-b-baby"
    ,"cacaw"
    ,"cagey"
    ,"cannoli"
    ,"capital"
    ,"captain"
    ,"cardio"
    ,"cha"
    ,"cha-chomp"
    ,"chaps"
    ,"cheekers"
    ,"cheeky"
    ,"cheepers"
    ,"cheeseball"
    ,"chickadee"
    ,"chicky poo"
    ,"child"
    ,"chimpy"
    ,"chipmunk"
    ,"chips"
    ,"chow down"
    ,"chuurp"
    ,"chuuuuurp"
    ,"chicken"
    ,"chicklet"
    ,"cluckadoo"
    ,"cluckling"
    ,"cool cat"
    ,"cottontail"
    ,"crisp"
    ,"croak-kay"
    ,"crunch"
    ,"crushy"
    ,"cubbie"
    ,"cubby"
    ,"cud"
    ,"clip-clawp"
    ,"check it"
    ,"daahling"
    ,"dahling"
    ,"dagnaabit"
    ,"dawayo"
    ,"dawg"
    ,"dearie"
    ,"deelish"
    ,"derrrrr"
    ,"doyoing"
    ,"duckling"
    ,"ducky"
    ,"duuude"
    ,"doodle-duh"
    ,"d-d-dude"
    ,"eaglet"
    ,"eekers"
    ,"eeks"
    ,"eat it"
    ,"faboom"
    ,"feathers"
    ,"flexin"
    ,"foxtrot"
    ,"frappe"
    ,"fribbit"
    ,"fromage"
    ,"fuzzball"
    ,"fuzzers"
    ,"gahhhh"
    ,"girlfriend"
    ,"glimmer"
    ,"glitter"
    ,"graaagh"
    ,"greenhorn"
    ,"grrr"
    ,"grrRAH"
    ,"grr-ribbit"
    ,"grrrolf"
    ,"gruff"
    ,"grumble"
    ,"gronk"
    ,"grooof"
    ,"grooomph"
    ,"groovy"
    ,"growf"
    ,"g'tang"
    ,"gumdrop"
    ,"guvnor"
    ,"haaay"
    ,"hammie"
    ,"harrumph"
    ,"hawkeye"
    ,"hay-OK"
    ,"h-h-hon"
    ,"heeeeeyy"
    ,"highness"
    ,"hippie"
    ,"hipster"
    ,"honey"
    ,"honeybun"
    ,"honk"
    ,"honk honk"
    ,"hoof hoo"
    ,"hoo-rah"
    ,"hopalong"
    ,"hopper"
    ,"how now"
    ,"hubbub"
    ,"hulaaaa"
    ,"hurk"
    ,"hot dog"
    ,"indeed"
    ,"indeedaroo"
    ,"it'sa me"
    ,"karat"
    ,"kerPOW"
    ,"kid"
    ,"kidders"
    ,"kitten"
    ,"kitty cat"
    ,"krzzt"
    ,"lambchop"
    ,"la baa"
    ,"laddie"
    ,"la-di-da"
    ,"lambkins"
    ,"le ham"
    ,"like whoa"
    ,"li'l bear"
    ,"li'l dude"
    ,"li'l ears"
    ,"li'l hare"
    ,"lion cub"
    ,"little one"
    ,"maaan"
    ,"macmoo"
    ,"mango"
    ,"mate"
    ,"meooo-Oh"
    ,"mew"
    ,"me-WOW"
    ,"me-YOWZA"
    ,"mimimi"
    ,"monch"
    ,"mon chou"
    ,"moocher"
    ,"moo-dude"
    ,"moolah"
    ,"munchie"
    ,"me meow"
    ,"mrmpht"
    ,"mrowrr"
    ,"myawn"
    ,"mweee"
    ,"my dear"
    ,"myohmy"
    ,"my pet"
    ,"natch"
    ,"nay"
    ,"nee-deep"
    ,"neighbor"
    ,"niblet"
    ,"nightshade"
    ,"no-doubt"
    ,"non"
    ,"nougat"
    ,"nutcase"
    ,"nutlet"
    ,"nutmeg"
    ,"nutty"
    ,"nyoink"
    ,"nuh uh"
    ,"no doy"
    ,"nyet"
    ,"okey-dokey"
    ,"ol' bear"
    ,"pah"
    ,"pal"
    ,"padner"
    ,"peach"
    ,"pffffft"
    ,"picante"
    ,"pine nut"
    ,"pinky"
    ,"pipsqueak"
    ,"pockets"
    ,"po po"
    ,"pouches"
    ,"powderpuff"
    ,"precisely"
    ,"pronk"
    ,"psst"
    ,"pthhhpth"
    ,"pudgy"
    ,"puh-lease"
    ,"punches"
    ,"punk"
    ,"purrr"
    ,"purrty"
    ,"pushy"
    ,"quaa"
    ,"quacker"
    ,"quackidee"
    ,"quackle"
    ,"quacko"
    ,"quackpth"
    ,"quackulous"
    ,"quite so"
    ,"rah rah"
    ,"rainbow"
    ,"reeeeOWR"
    ,"rerack"
    ,"ribette"
    ,"ridukulous"
    ,"rockin'"
    ,"rookie"
    ,"rooooowf"
    ,"rrr-owch"
    ,"ruffian"
    ,"saltlick"
    ,"schep"
    ,"schnort"
    ,"schnozzle"
    ,"shearly"
    ,"shortcake",
    ,"shorty"
    ,"shweetie"
    ,"sidekick"
    ,"silly"
    ,"sparkles"
    ,"sparky"
    ,"skraaaaw"
    ,"skree-haw"
    ,"slacker"
    ,"slushie"
    ,"sluuuurp"
    ,"snacky"
    ,"snappy"
    ,"snarrrl"
    ,"snifffff"
    ,"snoozit"
    ,"snoooink"
    ,"snooooof"
    ,"snoot"
    ,"snork"
    ,"snort"
    ,"snortie"
    ,"snortle"
    ,"snorty"
    ,"snoutie"
    ,"snuffle"
    ,"so it goes"
    ,"sooey"
    ,"speedy"
    ,"splish"
    ,"squeaky"
    ,"squee"
    ,"squinky"
    ,"squirt"
    ,"stretch"
    ,"strudel"
    ,"stubble"
    ,"stuffin'"
    ,"sucker"
    ,"sugar"
    ,"sugarbill"
    ,"sugar cube"
    ,"sulky"
    ,"sundae"
    ,"sunshine"
    ,"sweatband"
    ,"sweetie"
    ,"sweet pea"
    ,"swine"
    ,"tarnation"
    ,"teacup"
    ,"tenderfoot"
    ,"thump"
    ,"thumper"
    ,"tralala"
    ,"toady"
    ,"toasty"
    ,"tokana"
    ,"tooooot"
    ,"tootie"
    ,"tee-hee"
    ,"ten-hut"
    ,"toots"
    ,"tsk tsk"
    ,"tu-tutu"
    ,"tweedledee"
    ,"twinkles"
    ,"urgh"
    ,"unh-hunh"
    ,"uni-wow"
    ,"uff da"
    ,"ohmmm"
    ,"otaku"
    ,"oh bow"
    ,"oh ewe"
    ,"ol' bunny"
    ,"ooh la la"
    ,"oui oui"
    ,"uh-hoo"
    ,"uh-oh"
    ,"villain"
    ,"vroom"
    ,"waddler"
    ,"wee baby"
    ,"weeweewee"
    ,"whatevs"
    ,"whee"
    ,"whiffa"
    ,"whiskers"
    ,"whonk"
    ,"what what"
    ,"wingo"
    ,"woof"
    ,"woo-oo"
    ,"woo woof"
    ,"wee one"
    ,"wuh"
    ,"wut"
    ,"yelp"
    ,"yeah buddy"
    ,"yip yip"
    ,"yippee"
    ,"y'all"
    ,"ya heard"
    ,"ya know"
    ,"yaruwane"
    ,"yawwwn"
    ,"yodelay"
    ,"yo yo yo"
    ,"zip zoom"
    ,"zoink"
    ,"zort"
    ,"zut alors"
    ,"zzrrbbitt"
    ,"zzzook"
]